version: "3.7"

services:
  backend:
    container_name: backend
    restart: always
    volumes:
      - ./backend:/backend
    environment:
      DJANGO_SETTINGS_MODULE: backend.settings.deploy
    env_file:
      - .env
    build: ./backend

    ports:
      - "8000:8000"
    networks:
      - local-net
  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - ./backend/.media_root:/backend/.media_root
      - ./backend/static:/backend/static
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - local-net

#volumes:
#  static:

networks:
  local-net:
    driver: bridge
