version: "3.7"

services:
  mysql:
    container_name: mysql
    build: ./mysql
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --range_optimizer_max_mem_size=16777216
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    networks:
      - local-net

  backend:
    container_name: backend
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./backend:/backend
    environment:
      DJANGO_SETTINGS_MODULE: backend.settings.develop
    env_file:
      - .env
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - local-net
  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - ./backend/.media_root:/backend/.media_root
      - ./backend/static:/backend/static
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - local-net

#volumes:
#  static:

networks:
  local-net:
    driver: bridge