name: PR Test [Service]

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: |
        git fetch
        ls -al
        touch .env
        echo "${{ secrets.ENV_VARS }}" >> .env
        docker-compose up --build
        
