name: PR Test [Service]

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  Test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        touch .env
        echo "${{ secrets.ENV_VARS }}" >> .env
        docker-compose up -d --build
        docker exec backend python manage.py wait_for_db
        
    - name: Migrations
      run: |
        docker exec backend python manage.py makemigrations user product order payment
        docker exec backend python manage.py migrate

    - name: Test
      run: |
        docker exec backend python manage.py test tests/
        
