name: Deploy to EC2

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: create env file
      run: |
        touch .env
        echo "${{ secrets.ENV_VARS }}" >> .env
    
    - name: create remote directory
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_NAME }}
        username: ubuntu
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        script: mkdir -p /home/ubuntu/github
        
    - name: copy source via ssh key
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        remote_path: /home/ubuntu/github/
        remote_host: ${{ secrets.HOST_NAME }}
        remote_user: ubuntu
        remote_key: ${{ secrets.AWS_PRIVATE_KEY }}
        
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_NAME }}
        username: ubuntu
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        script: |
          sh /home/ubuntu/github/deploy/deploy.sh
