name: Deploy to EC2

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: create env file
      env:
          MATRIX_CONTEXT: ${{ secrets.AWS_PRIVATE_KEY }}
      run: |
        touch .env
        touch .secret
        echo "${{ secrets.ENV_VARS }}" >> .env
        echo "${{ secrets.AWS_PRIVATE_KEY }}" >> .secret
