name: Deploy to EC2

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: checkout

      env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOST  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            ENV_VARS : ${{ secrets.ENV_VARS  }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

          cd /home/ubuntu/e-commerce &&
          git checkout develop &&
          git fetch --all &&
          git reset --hard origin/develop &&
          git pull origin develop &&
          sudo docker-compose -f docker-compose.prod.yml up -d --build 
        '
