name: Deploy to EC2

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: create env file
      env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOST  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            ENV_VARS : ${{ secrets.ENV_VARS  }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}

        cd /home/ubuntu &&
        touch .env
        touch .secret
        echo "${{ secrets.ENV_VARS }}" >> .env
        echo "${{ secrets.AWS_PRIVATE_KEY }}" >> .secret
